import bcrypt from 'bcryptjs';

const data = {
  users:[
    {
      name:'Mimika',
      email:'MimikaAckerman@gmail.com',
      password:bcrypt.hashSync('123456'),
      isAdmin:true,
    },
    {
      name:'Levi Ackerman',
      email:'LeviAckerman@gmail.com',
      password:bcrypt.hashSync('123456'),
      isAdmin:false,
    }
  ],
  products: [
    {
      name: "Eyes Cup",
      slug: "Eyes-cup",
      category: "Cups",
      image: "/images/cup1.jpg",
      price: 15,
      brand:'☕',
      rating: '⭐⭐⭐⭐⭐',
      numReviews: 8,
      countInStock: 5,
      description: "A popular Cup",
      isFeatured: true,
    },
    {
      name: "Boobs Cup",
      slug: "Boobs-cup",
      category: "Cups",
      image: "/images/cup2.jpg",
      price: 15,
      brand:'☕',
      rating: '⭐⭐⭐⭐⭐',
      numReviews: 8,
      countInStock: 10,
      description: "A popular Cup",
      isFeatured: true,
    },
    {
      name: "Butterfly Cup",
      slug: "Butterfly-cup",
      category: "Cups",
      image: "/images/cup3.jpg",
      price: 15,
      brand:'☕',
      rating: '⭐⭐⭐',
      numReviews: 8,
      countInStock: 5,
      description: "A popular Cup",
      isFeatured: true,
    },
    {
      name: "Lazy Cup",
      slug: "Lazy-cup",
      category: "Cups",
      image: "/images/cup4.jpg",
      price: 15,
      brand:'☕',
      rating: '⭐⭐',
      numReviews: 8,
      countInStock: 3,
      description: "A popular Cup",
      isFeatured: true,
    },
    {
        name: "Face Cup",
        slug: "Face-cup",
        category: "Cups",
        image: "/images/cup5.jpg",
        price: 15,
        brand:'☕',
        rating: '⭐⭐⭐⭐',
        numReviews: 8,
        countInStock: 5,
        description: "A popular Cup",
        isFeatured: true,  
    },
    {
        name: "Bird Cup",
        slug: "Bird-cup",
        category: "Cups",
        image: "/images/cup6.jpg",
        price: 15,
        brand:'☕',
        rating: '⭐',
        numReviews: 8,
        countInStock: 10,
        description: "A popular Cup",
        isFeatured: true, 
    },
    {
        name: "Astract plant",
        slug: "Astract-plant",
        category: "Cups",
        image: "/images/plant1.jpg",
        price: 15,
        brand:'🪴',
        rating: '⭐⭐⭐⭐⭐',
        numReviews: 8,
        countInStock: 20,
        description: "A popular Cup",
        isFeatured: true,   
    },
    {
        name: "Noodles Plant",
        slug: "Noodles-plant",
        category: "Cups",
        image: "/images/plant2.jpg",
        price: 15,
        brand:'🪴',
        rating: '⭐⭐',
        numReviews: 8,
        countInStock: 20,
        description: "A popular Cup",
        isFeatured: true, 
    },
    {
        name: "Live Plant",
        slug: "Live-plant",
        category: "Cups",
        image: "/images/plant3.jpg",
        price: 15,
        brand:'🪴',
        rating: '⭐',
        numReviews: 8,
        countInStock: 20,
        description: "A popular Cup",
        isFeatured: true, 
    },
    {
        name: "Money Plant",
        slug: "Money-plant",
        category: "Cups",
        image: "/images/plant4.jpg",
        price: 15,
        brand:'🪴',
        rating: '⭐⭐',
        numReviews: 8,
        countInStock: 20,
        description: "A popular Cup",
        isFeatured: true, 
    },
    {
        name: "Love Plant",
        slug: "Love-plant",
        category: "Cups",
        image: "/images/plant5.jpg",
        price: 15,
        brand:'🪴',
        rating: '⭐⭐⭐⭐',
        numReviews: 8,
        countInStock: 20,
        description: "A popular Cup",
        isFeatured: true, 
    },
    {
        name: "Animal Plant",
        slug: "Animal-plant",
        category: "Cups",
        image: "/images/plant6.jpg",
        price: 15,
        brand:'🪴',
        rating: '⭐⭐⭐⭐⭐',
        numReviews: 8,
        countInStock: 20,
        description: "A popular Cup",
        isFeatured: true, 
    }
  ],
};


export default data;
